### ISSUE TITLE
Excludes Ignored at 1.1.0

### ISSUE THREAD

**Issue by KMC13** [dougmoscrop/serverless-plugin-include-dependencies#1]
Firstly, thank you for producing this plugin it is really useful. 

Unfortunately at the latest version 1.1.0 I am finding that all my package excludes are being included in the package. 

I have not identified why this is happening yet.

**Comment by dougmoscrop** [comment]
Oh no! If you could provide any details that would be great, I'll have a look.

**Comment by KMC13** [comment]
I think it is this line:
dependencies[current] = path.join(current, '**');

As the includes override the excludes this I think adds all files excluded back in. https://serverless.com/framework/docs/providers/aws/guide/packaging/

**Comment by dougmoscrop** [comment]
It will, but only for the 'current' path which is of some module.

So yeah if you have say module foo.. and in your handler.js you
require('foo'), it will add node_modules/foo/** to the include. Are you
trying to exclude something within node_modules/foo/__ ?

**Comment by KMC13** [comment]
No I dont think so. 

Here are my dependencies:
"dependencies": {
    "aws-sdk": "^2.7.13",
    "dotenv": "^2.0.0",
    "dynogels": "^6.1.1",
    "dynogels-promisified": "^1.0.3",
    "halson": "^2.3.1",
    "joi": "^10.0.6",
    "lodash": "^4.17.2"
  },

This is the resultant include list (Shortened):
`[ 'src/**',
     'handler.js',
     '**',
     'node_modules\\lodash\\**',
     'node_modules\\joi\\**',
     'node_modules\\topo\\**',
     'node_modules\\hoek\\**',
     'node_modules\\items\\**',
     'node_modules\\isemail\\**',
     'node_modules\\halson\\**',
     'node_modules\\dynogels-promisified\\**',
     'node_modules\\bluebird\\**' ]`

It's the first ** that forces the inclusion of everything.
So, it must be including the root as a module I guess.
And current must be empty.

**Comment by dougmoscrop** [comment]
Thanks, will investigate!

**Comment by KMC13** [comment]
Given it a try and all good now. Awesome stuff thank you.
