### ISSUE TITLE
Deprecated API used

### ISSUE THREAD

**Issue by martinheidegger** [dougmoscrop/serverless-plugin-include-dependencies#15]
When running serverless deployment it complains with: `Serverless: WARNING: Plugin IncludeDependencies uses deprecated hook before:deploy:createDeploymentArtifacts`

**Comment by jmalins** [comment]
Hi, I appreciate the plugin.

Will there be an NPM release with this fix?

**Comment by dougmoscrop** [comment]
yes, whoops!

**Comment by dougmoscrop** [comment]
done as 3.0.0

**Comment by jmalins** [comment]
Great, thanks! 👍
