### ISSUE TITLE
issue with the installing serverless-plugin

### ISSUE THREAD

**Issue by clock21am** [dougmoscrop/serverless-plugin-include-dependencies#19]
the commands that are being mentioned in your readme are not installing the serverless plugin. that will only install the npm package. 
In short, that will add a node devDependency of the nodejs module.
please add this line 
sls plugin install --name (your-package-name)

**Comment by dougmoscrop** [comment]
I'll try to get around to this, but would welcome a PR too if you have the time.

**Comment by dougmoscrop** [comment]
The README includes adding it to serverless.yml: https://github.com/dougmoscrop/serverless-plugin-include-dependencies/blame/master/README.md#L33
