### ISSUE TITLE
[Question] What's the use of utils.isOutside ?

### ISSUE THREAD

**Issue by hlefebvr** [dougmoscrop/serverless-plugin-include-dependencies#23]
Hello there and thanks for the good work ! 

I'm currently developing a project with the serverless framework and the excellent [lerna.js](https://github.com/lerna/lerna) which allows you to create "local" dependencies and share code between modules. 

Due to its working logic (creating symbolic links and setting dependency in package.json), using serverless-plugin-include-dependecies failed at first because of utils.isOutside which throwed an error saying that the file was out of the current directory (which is legit). However, when replacing this function's logic with a simple and unconditional `return false`, I get to deploy my project and reduce (considerably) its serverless.zip size. 

Hence my question, what was the original purpose of this function ? 

Thanks !

**Comment by dougmoscrop** [comment]
What *was" happening and may not anymore, was the path of the file gets
resolved to it's actually path, not the symlink. Upon deploy, the
serverless zip had the source files in the wrong path.

I didn't want the packaging step to quietly break deployment so I added
this as a safeguard.

It's worth revisiting for sure just haven't had time.

**Comment by hlefebvr** [comment]
Hm, I understand. It does not seem to be the case anymore. 

Should I PR with a version with utils.isOutside being removed ? 
Or else, use environment variable to disable or enable this safeguard ?

**Comment by dougmoscrop** [comment]
We can remove it but testing is super important. This is a pretty widely
used plugin and we don't wanna break things!

Writing integration tests for serverless isn't super easy but it can be
done. I would normally do it I'm just super swamped right now, so if you PR
with just the code change it's gonna sit for a but before I can get around
to testing etc

**Comment by joscha** [comment]
> @joscha does your change in #24 just make your symlink stuff work?

As a side-effect, yes - we have some `NODE_PATH` extensions set up, which are symlinks. There might be some special cases that are not caught by m change potentially.

**Comment by dougmoscrop** [comment]
Can you try with `3.2.0`? I just published it. I tested locally and it worked with a symlinked dependency.

**Comment by dougmoscrop** [comment]
Has been removed, please re-open if the fix isn't working!
