### ISSUE TITLE
include external dependencies

### ISSUE THREAD

**Issue by samikarak** [dougmoscrop/serverless-plugin-include-dependencies#28]
In my current application I have db models, which gets shared by each serverless application. I would like to include these external models in my serverless deployment

// handler.js
const myModel = require('../models/myModel.model');

Is that possible with this plugin ? If not, is this a feature you would consider to integrate ?

**Comment by dougmoscrop** [comment]
Sorry I somehow missed this issue. I don't think I understand the request, can you give more detailed example?

**Comment by jmonster** [comment]
I believe they're asking if they can include their own files and not just nom dependencies -- which is something offered by specifying `Webpack: true` in the dot-yaml-file

**Comment by dougmoscrop** [comment]
Oh, the simplest way to achieve this would just be to use severless' built-in support?

like

package:
  include:
    src/**/*.model

**Comment by dougmoscrop** [comment]
Okay I think this issue is solved using native Serverless support, closing, but if there's something this plugin can do that makes it easier than a one liner ^ please reopen with requirements etc
