### ISSUE TITLE
Bug: getHandlerFilename lastIndexOf

### ISSUE THREAD

**Issue by vbryan** [dougmoscrop/serverless-plugin-include-dependencies#33]
There's bug for google cloud functions.
Example:
serverless.yml:
`functions:`
`  exportProduct:`
`    handler: exportProduct`

getHandlerFilename(hanlder) returns exportProduc

Possible solution:
`getHandlerFilename(handler) {`
`    const lastDotIndex = handler.lastIndexOf('.');`
`    const handlerPath = handler.slice(0, lastDotIndex !== -1 ? lastDotIndex : 0);`
`    return require.resolve((path.join(this.serverless.config.servicePath, handlerPath)));`
`  }`

**Comment by dougmoscrop** [comment]
I don't use GCP but if you can contribute a fix I would happily merge this

**Comment by aychtang** [comment]
@dougmoscrop I think we can close this due to #55

**Comment by dougmoscrop** [comment]
Sounds good, feel free to reopen if needed!
