### ISSUE TITLE
Fails when used with typeorm package

### ISSUE THREAD

**Issue by eob** [dougmoscrop/serverless-plugin-include-dependencies#4]
When I try to use this plugin with the `typeorm` npm package, something gets weird with the packaging and I get the following error:

```
 Error --------------------------------------------------

     Cannot find module '@types/node' from '/Users/eob/Code/cloudstitch3/node_modules/typeorm'
```

To reproduce, just try to build and deploy a project with `typeorm`

**Comment by dougmoscrop** [comment]
I think the dependency from typeorm was removed that caused this, but still, I've published v1.2.2 that should fix this and requires no additional configuration.
