### ISSUE TITLE
exclude aws-sdk by default

### ISSUE THREAD

**Issue by elgubenis** [dougmoscrop/serverless-plugin-include-dependencies#5]
hi, would there be an easy way to exclude the aws-sdk? since it does already exist in the node runtime? maybe a flag or options to force excluding even if its listed as a depedency of a dependency

**Comment by dougmoscrop** [comment]
ah sorry, this was a feature and I must have forgot to keep it when I
refactored; I will add it back (and a regression test ;))

**Comment by elgubenis** [comment]
oh yeah, i see: https://github.com/dougmoscrop/serverless-plugin-include-dependencies/blob/v1.0.1/include-dependencies.js#L32
