### ISSUE TITLE
Improve error message for: Could not find ${moduleName}

### ISSUE THREAD

**Issue by aychtang** [dougmoscrop/serverless-plugin-include-dependencies#58]
I had a build error where I had this message:

```
Error: [serverless-plugin-include-dependencies]: Could not find critters
```

And had no real idea what it meant until looking into the source code for this package, @dougmoscrop shall we change it to something like:

```
Error: [serverless-plugin-include-dependencies]: Could not find npm package ${moduleName}
```

Happy to make the change + pr if needed.

**Comment by pakorn-tp** [comment]
@aychtang  I support this issue. I spend my time about 3 hours for fix error message "Could not find request"

**Comment by aychtang** [comment]
@pakorn-tp @dougmoscrop: Definitely seems like this can cause confusion. Since someone else has also had this issue now I'll create a fix PR

**Comment by aychtang** [comment]
@dougmoscrop: I've added a PR @ https://github.com/dougmoscrop/serverless-plugin-include-dependencies/pull/70.
