### ISSUE TITLE
5.1 accidentally omits some dependencies for individually packaged functions

### ISSUE THREAD

**Issue by oezi** [dougmoscrop/serverless-plugin-include-dependencies#81]
Setup:
- two different functions, each importing/requireing some dependencies the other one doesn't use
- a "utils"-folder containig some common methods. These utils also import/require some dependencies

Result:
- the function that gets processed and packaged first works: it contains all its direct dependencies and all dependencies needed for the util-methods it uses
- every function thereafter is incomplete: it contains only its direct dependencies, the dependencies needed for the util-methods it uses are missing from the package

Reason: pull-request #80 (merged in https://github.com/dougmoscrop/serverless-plugin-include-dependencies/commit/5219162301a6bec3416c750c2110c54fcd9daf0c and released with version 5.1) introduced the "checkedFiles"-Set. This Set does _not_ get cleared before/after processing the next function. In my example above, when getDependencyList for the second function gets called, the util-Files are already present in this Set und thus get skipped - wich leads to missing the dependencies only used by the utils.

possible (hacky) fixes:
- add "checkedFiles.clear()" befor ar after "processFunction"-call within "createDeploymentArtifacts()"
- change "if (filePaths.has(currentLocalFile) || checkedFiles.has(currentLocalFile))" to "if (filePaths.has(currentLocalFile) **&&** checkedFiles.has(currentLocalFile))" or "if (filePaths.has(currentLocalFile))" within "getDependencyList"

both of the fixes work for my usecase, but probably mess with the intend of #80 - i'm new to this project, so i'm not sure, what a good/correct fix would look like. Maybe @tenbradley as the author of #80 can help here. I could also do some more tests and create a pull-request with one of my solutions, if @dougmoscrop wants me to do so.

**Comment by baloran** [comment]
Same problem here ! Two fonction with same import doesn't import same node_modules

**Comment by KingSheamus** [comment]
Also the same here after an Upgrade to Version 5.1.
With version 5.0 it seems to work..thats why I just downgraded back to 5.0

**Comment by dougmoscrop** [comment]
I've marked 5.1 as deprecated so it won't be installed anymore while we fix things.
